import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import getdata from "../api/posts/getdata";
import { PrismaClient } from "@prisma/client";
import Layout from "../../layout/layout";
import Router from "next/router";


const About: NextPage = () => {

  const submitContact = async (event) => {
    event.preventDefault();
    const data = {
      title: event.target.title.value,
      body: event.target.body.value 
    }
    const JSONdata = JSON.stringify(data)
    const options = {
      method: "POST",
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSONdata,
    }
    const response = await fetch("/api/posts/add",options)
    const result = await response.json()

    if(response.status == 200){
      Router.push('/')
    }
  };

  return (
    <Layout>
      <Head>
        <title>Add Post</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Add <span className="text-[hsl(280,100%,70%)]">Post</span>
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
          <form onSubmit={submitContact} method="post">
            <label for="title" className="text-white">Title</label>
            <input
              type="text"
              id="title"
              name="title"
              required
            />
            <br/>
            <label for="body" className="text-white">Body:</label>
            <input type="text" id="body" name="body" required />
            <button type="submit" className="text-white">Submit</button>
          </form>
          </div>
        </div>
      </main>
    </Layout>
  );
};

export default About;
