import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import getdata from "./api/posts/getdata";
import { PrismaClient } from "@prisma/client";
import Layout from "../layout/layout";

export async function getStaticProps() {
  const res = await fetch(`http://localhost:3000/api/getdata`);
  const res2 = await fetch("https://jsonplaceholder.typicode.com/posts");

  const allPostsData = await res.json();
  const allPostsData2 = await res2.json();
  return {
    props: {
        allPostsData,
    }
  };
}

const About: NextPage = ({allPostsData}) => {

  return (
    <Layout>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Create <span className="text-[hsl(280,100%,70%)]">T3</span>
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
          <ul className="text-white">
            {allPostsData.map(({id, title, body})=>(
              <li>
              {id}
              {title}
              <br/>
              {body}
              </li>
            ))}
          </ul>
          </div>
        </div>
      </main>
    </Layout>
  );
};

export default About;
