import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import getdata from "./api/posts/getdata";
import { PrismaClient } from "@prisma/client";
import Layout from "../layout/layout";

export async function getStaticProps() {
  const res = await fetch(`http://localhost:3000/api/posts/getdata`);

  const allPostsData = await res.json();
  return {
    props: {
        allPostsData,
    }
  };
}

const Home: NextPage = ({allPostsData}) => {

  return (
    <Layout>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  <div className="relative overflow-hidden bg-no-repeat bg-cover" style={{
    backgroundPosition: "50%",
    backgroundImage: "url('https://mdbcdn.b-cdn.net/img/new/slides/146.webp')",
    height: "350px",
  }}>
    <div className="absolute top-0 right-0 bottom-0 left-0 w-full h-full overflow-hidden bg-fixed"
      style={{backgroundColor: "rgba(0, 0, 0, 0.75)"}}>
      <div className="flex justify-center items-center h-full">
        <div className="text-center text-white px-6 md:px-12">
          <h1 className="text-5xl font-bold mt-0 mb-6">Heading</h1>
          <h3 className="text-3xl font-bold mb-8">Test</h3>
          <button type="button"
            className="inline-block px-6 py-2.5 border-2 border-white text-white font-medium text-xs leading-tight uppercase rounded hover:bg-black hover:bg-opacity-5 focus:outline-none focus:ring-0 transition duration-150 ease-in-out"
            data-mdb-ripple="true" data-mdb-ripple-color="light">
            Get started
          </button>
        </div>
      </div>
    </div>
  </div>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Welcome <span className="text-[hsl(280,100%,70%)]">Pick your Post</span>!
          </h1>
          
          <div className="flex justify-center gap-4 grid grid-cols-3">
          {allPostsData.map(({id, title, body})=>(
            <div className="flex flex-col md:flex-row md:max-w-xl rounded-lg bg-white shadow-lg" key={id}>
              <img className=" w-full h-96 md:h-auto object-cover md:w-48 rounded-t-lg md:rounded-none md:rounded-l-lg" src="https://mdbootstrap.com/wp-content/uploads/2020/06/vertical.jpg" alt="" />
              <div className="p-6 flex flex-col justify-start">
                <Link href={'posts/'+id} className="text-gray-900 text-xl font-medium mb-2">{title}</Link>
                <p className="text-gray-700 text-base mb-4">
                  {body}
                </p>
                <p className="text-gray-600 text-xs">Last updated 3 mins ago</p>
              </div>
            </div>
            ))}
          </div>

        </div>
      </main>
    </Layout>
  );
};

export default Home;
